// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBafJ4Mc_gRcW2wIbT-uDaRo_8W0Rbhug0',
    appId: '1:684929320335:web:59fee9e38c6a49415037fa',
    messagingSenderId: '684929320335',
    projectId: 'belp-b164e',
    authDomain: 'belp-b164e.firebaseapp.com',
    storageBucket: 'belp-b164e.appspot.com',
    measurementId: 'G-SQRWQ9FYXW',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDtQ5uq3DPy6etXIRtmwoJ3qPXjQBWtL5A',
    appId: '1:684929320335:android:dcf7d9ffb66bd9d45037fa',
    messagingSenderId: '684929320335',
    projectId: 'belp-b164e',
    storageBucket: 'belp-b164e.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA6003xQ3ptlE7R9hnQewoEQm78CAvkRoQ',
    appId: '1:684929320335:ios:b994fa0fbd73b93e5037fa',
    messagingSenderId: '684929320335',
    projectId: 'belp-b164e',
    storageBucket: 'belp-b164e.appspot.com',
    androidClientId: '684929320335-b2k3mi6jdl2lmjr0ed0v0pks6qcga6nk.apps.googleusercontent.com',
    iosClientId: '684929320335-oou2kokopnagiph6b4dgr2u4olhhndut.apps.googleusercontent.com',
    iosBundleId: 'com.example.socialMediaApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA6003xQ3ptlE7R9hnQewoEQm78CAvkRoQ',
    appId: '1:684929320335:ios:b994fa0fbd73b93e5037fa',
    messagingSenderId: '684929320335',
    projectId: 'belp-b164e',
    storageBucket: 'belp-b164e.appspot.com',
    androidClientId: '684929320335-b2k3mi6jdl2lmjr0ed0v0pks6qcga6nk.apps.googleusercontent.com',
    iosClientId: '684929320335-oou2kokopnagiph6b4dgr2u4olhhndut.apps.googleusercontent.com',
    iosBundleId: 'com.example.socialMediaApp',
  );
}
